### ISSUE TITLE
ng build --prod issue on angular 8

### ISSUE THREAD

**Issue by arkabhowmick** [vitalii-andriiovskyi/ngx-owl-carousel-o#160]
Hi,
I get the following issue while doing ng build --prod..
```ERROR in ./node_modules/ngx-owl-carousel-o/fesm2015/ngx-owl-carousel-o.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
    at checkNodeForDecorators (/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
    at visitNodes (/node_modules/typescript/lib/typescript.js:16514:30)
    at Object.forEachChild (/node_modules/typescript/lib/typescript.js:16740:24)
    at checkNodeForDecorators (/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/node_modules/typescript/lib/typescript.js:16635:21)
    at checkNodeForDecorators (/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/node_modules/typescript/lib/typescript.js:16703:24)
    at checkNodeForDecorators (/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/node_modules/typescript/lib/typescript.js:16692:24)
    at checkNodeForDecorators (/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/node_modules/typescript/lib/typescript.js:16599:21)
```
Any solution for this ? 
Following are the project version.
Angular 8.1.1
"ngx-owl-carousel-o": "^2.1.1",

**Comment by vitalii-andriiovskyi** [comment]
@arkabhowmick 

That is strange, because my testing app with Angular 8 builds good. Maybe is something wrong with the version of `@angular-devkit` you're using in your project.

**Comment by arkabhowmick** [comment]
Yeah.. looks like an angular issue and not carousel issue.
Upgraded Angular to 11. No issue in build.
