### ISSUE TITLE
NullInjectorError: No Provider for ResizeService in microfrontend application

### ISSUE THREAD

**Issue by nani554** [vitalii-andriiovskyi/ngx-owl-carousel-o#274]
`Start of NullInjectorError: R3InjectorError(CustomerModule)ResizeService -> ResizeService => ResizeService -> ResizeService]: NullInjectorError: No provider for ResizeService!`

Im using "**@angular-architects/module-federation**" thus making a monolithic application to microfrontend app.
I've **host** repository and **remote** repository and in both repositories **CarousalModule** is imported in module file, and in run time as soon as i navigate to remote repository with initialized component which is using **<owl-carousel-o  ***>...**.
as soon as this element is rendered, application is crashing and printing above message in console.

node: v16.15.1
**angular: 14.0.0**
"@angular-architects/module-federation": "14.3.0",   
"@angular-architects/module-federation-tools": "14.3.0",
**"ngx-owl-carousel-o": "14.0.0"**,

Need your support in resolving this issue, please feel free to ask any questions.
Thank you

**Comment by BEST-Thanawat** [comment]
Hi,

Just add "importProvidersFrom([CarouselModule])" into providers in app.config.ts.

**Comment by nani554** [comment]
We dont have app.config.ts in angular application, so i dont know exactly where to add it, when adding it in routes.ts
  {
    path: 'customers',
    providers: [ importProvidersFrom([CarouselModule]) ],
    loadChildren: () => 
    loadRemoteModule({
     type: 'module',
     remoteEntry: `${ENVIRONMENT.ccContextPath}/remoteEntry.js`,
     exposedModule: "./CCWebComponents",
   }).then((m) => m.CustomerModule)
  },
  
  im getting following error:

NullInjectorError: R3InjectorError(CreditCardModule)[ResizeService -> EventManager -> EventManager -> EventManager -> EventManager -> EventManager]: 
  NullInjectorError: No provider for EventManager!
    at NullInjector.get (core.mjs:9131:27)
    at R3Injector.get (core.mjs:9298:33)
    at R3Injector.get (core.mjs:9298:33)
    at R3Injector.get (core.mjs:9298:33)
    at R3Injector.get (core.mjs:9298:33)
    at R3Injector.get (core.mjs:9298:33)
    at injectInjectorOnly (core.mjs:4869:33)
    at Module.ɵɵinject (core.mjs:4873:12)
    at Object.ResizeService_Factory [as factory] (ngx-owl-carousel-o.mjs:2613:1)
    at R3Injector.hydrate (core.mjs:9393:35) 'NullInjectorError: R3InjectorError(CreditCardModule)[ResizeService -> EventManager -> EventManager -> EventManager -> EventManager -> EventManager]: \n  NullInjectorError: No provider for EventManager!'
	
	
	note: please let me know where exactly i've to provide it, if im providing it in correct way then could you please help me in resolving this issue as well.
	. CustomerModule is seperate repository, in that repository only im using carousal, so basically when im navigating to customer repository from host repository and when carousal is rendering im facing this issue.
	
	Thank you @BEST-Thanawat

**Comment by nani554** [comment]
ive resolved above issue by importing CarousalModule and now im facing following error

Error: NG0300: Multiple components match node with tagname owl-carousel-o: CarouselComponent and CarouselComponent. Find more at https://angular.io/errors/NG0300
    at throwMultipleComponentError (core.mjs:7002:11)
    at findDirectiveDefMatches (core.mjs:12561:29)
    at resolveDirectives (core.mjs:12374:31)
    at elementStartFirstCreatePass (core.mjs:15120:27)
    at ɵɵelementStart (core.mjs:15160:9)
    at CardSelectionComponent_section_0_div_1_div_2_Template (template.html:70:71)
    at executeTemplate (core.mjs:11744:9)
    at renderView (core.mjs:11544:13)
    at TemplateRef.createEmbeddedView (core.mjs:23383:9)
    at ViewContainerRef.createEmbeddedView (core.mjs:23501:37) 'Error: NG0300: Multiple components match node with tagname owl-carousel-o: CarouselComponent and CarouselComponent. Find more at https://angular.io/errors/NG0300'
    
    Could you please resolve this issue @BEST-Thanawat 

Thank you

**Comment by nani554** [comment]
Resolved above issue by removing CaraousalModule import from remote repository module
ref: https://stackoverflow.com/questions/60482442/multiple-components-match-node-with-tagname-app-lobby 

Thank you very much @BEST-Thanawat

**Comment by BEST-Thanawat** [comment]
> We dont have app.config.ts in angular application, so i dont know exactly where to add it for time being adding it in routes.ts { path: 'customers', providers: [ **importProvidersFrom([CarouselModule])** ], loadChildren: () => loadRemoteModule({ type: 'module', remoteEntry: `${ENVIRONMENT.ccContextPath}/remoteEntry.js`, exposedModule: "./CCWebComponents", }).then((m) => m.CustomerModule) },
> 
> ```
> note: please let me know where exactly i've to provide it
> . CustomerModule is seperate repository, in that repository only im using carousal, so basically when im navigating to customer repository from host repository and when carousal is rendering im facing this issue.
> ```
> 
> Thank you @BEST-Thanawat

Did you solve the issue?

I just migrated my old app in to Angular 17 (app.config.ts is in Angular 17) so which Angular version are you using?

**Comment by nani554** [comment]
No, couldnt resolve this issue,
Im using Angular 14

**Comment by nani554** [comment]
We have resolved it by moving carousel related functionality to shared module which is present in seperate repository, which we are using as a angular package(npm package) in remote and host repositories.
so in that package repo. we have created one component which contains carousel and exporting that component from sharedmodule.
