### ISSUE TITLE
Using Angular Universal 8, but can't apply the suggested fix

### ISSUE THREAD

**Issue by martinlombana** [vitalii-andriiovskyi/ngx-owl-carousel-o#71]
I already tried adding the code in the suggested fixes, but it simply doesn't work or raises other errors. I don't know if someone can share their package.json for an angular 8, using angular prerender... 

Thanks!

And I am getting the error 

```
 UnhandledPromiseRejectionWarning: ReferenceError: Event is not defined
    at D:\Sync\Martin\inProgress\eusko-cocina\repos\eusko-cocina-web\node_modules\ngx-owl-carousel-o\bundles\ngx-owl-carousel-o.umd.js:2991:46
    at D:\Sync\Martin\inProgress\eusko-cocina\repos\eusko-cocina-web\node_modules\ngx-owl-carousel-o\bundles\ngx-owl-carousel-o.umd.js:3023:6
    at D:\Sync\Martin\inProgress\eusko-cocina\repos\eusko-cocina-web\node_modules\ngx-owl-carousel-o\bundles\ngx-owl-carousel-o.umd.js:2:68
    at Object.<anonymous> (D:\Sync\Martin\inProgress\eusko-cocina\repos\eusko-cocina-web\node_modules\ngx-owl-carousel-o\bundles\ngx-owl-carousel-o.umd.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
(node:3556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

this is my package.json

```
{
  "name": "xxxx",
  "version": "1.0.1",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "prerender": "ng build --prod && ng run universe:server && npx angular-prerender",
    "mock": "ng serve --open"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/http": "^7.2.16",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/platform-server": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@ng-bootstrap/ng-bootstrap": "^5.3.0",
    "@nicky-lenaers/ngx-scroll-to": "^3.0.1",
    "bootstrap": "^4.4.1",
    "core-js": "^3.6.4",
    "hamburgers": "^1.1.3",
    "ngx-owl-carousel-o": "^2.0.3",
    "rxjs": "^6.5.4",
    "tslib": "^1.11.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.25",
    "@angular/cli": "^8.3.25",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/jasmine": "^3.5.6",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "^12.12.28",
    "angular-prerender": "^4.4.3",
    "codelyzer": "^5.2.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.2",
    "protractor": "^5.4.3",
    "ts-node": "~8.5.4",
    "tslint": "~5.20.1",
    "typescript": "~3.5.3"
  }
}

```

**Comment by martinlombana** [comment]
After hours of trying things, I had the brilliant idea of SIMPLY, adding:
global['Event'] = null; 

to the top

node_modules/ngx-owl-carousel-o/bundles/ngx-owl-carousel-o.umd.js

![image](https://user-images.githubusercontent.com/18351919/75080596-b4d44480-550c-11ea-8c0b-f4f771242d4a.png)

AND IT WORKED!

Can you please @vitalii-andriiovskyi  apply that fix in that file, which is trivial, for the next release?

Thanks.

**Comment by vitalii-andriiovskyi** [comment]
Published new versions of the lib which avoid the reason of the issue.

Choose the right version to your project using the [compatibility table](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o#compatibility).
